// Auto-generated by scripts/sync-chapters.mjs — do not edit manually

export type ChapterCategory = 'fundamentals' | 'building-blocks' | 'case-studies'

export interface Chapter {
  id: string
  order: number
  title: string
  subtitle: string
  category: ChapterCategory
  readTime: number
  imageCount: number
  sourceFolder: string
}

export const categories: { id: ChapterCategory; label: string; description: string }[] = [
  { id: 'fundamentals', label: 'Fundamentals', description: 'Scaling, estimation, and interview framework' },
  { id: 'building-blocks', label: 'Building Blocks', description: 'Rate limiters, hashing, KV stores, and ID generation' },
  { id: 'case-studies', label: 'Case Studies', description: 'End-to-end designs for real-world systems' },
]

export const chapters: Chapter[] = [
  {
    "id": "01-scaling",
    "order": 1,
    "title": "Chapter 1: Scale from Zero to Millions of Users",
    "subtitle": "Scaling a system to support millions of users is a complex, iterative journey requiring refinement and optimization. This chapter outlines how to begin with a s",
    "category": "fundamentals",
    "readTime": 8,
    "imageCount": 12,
    "sourceFolder": "01. Scaling"
  },
  {
    "id": "02-back-of-the-envelope-estimation",
    "order": 2,
    "title": "Chapter 2: Back-of-the-Envelope Estimation",
    "subtitle": "Back-of-the-envelope estimation is a crucial skill in system design interviews. It involves making quick, rough calculations to assess system capacity or perfor",
    "category": "fundamentals",
    "readTime": 5,
    "imageCount": 1,
    "sourceFolder": "02. Back Of the Envelope Estimation"
  },
  {
    "id": "03-system-design-framework",
    "order": 3,
    "title": "Chapter 3: A Framework for System Design Interviews",
    "subtitle": "System design interviews are a key part of the hiring process, simulating real-life problem-solving scenarios. These interviews evaluate not just technical skil",
    "category": "fundamentals",
    "readTime": 5,
    "imageCount": 0,
    "sourceFolder": "03. System Design Framework"
  },
  {
    "id": "04-rate-limiter",
    "order": 4,
    "title": "Chapter 4: Design a Rate Limiter",
    "subtitle": "This chapter explores the design and implementation of a rate limiter—a system component used to control traffic rates sent by clients or services. Rate limiter",
    "category": "building-blocks",
    "readTime": 5,
    "imageCount": 8,
    "sourceFolder": "04. Rate Limiter"
  },
  {
    "id": "05-consistent-hashing",
    "order": 5,
    "title": "Chapter 5: Design Consistent Hashing",
    "subtitle": "This chapter explores consistent hashing, a technique essential for achieving horizontal scaling by efficiently distributing requests and data across servers. I",
    "category": "building-blocks",
    "readTime": 5,
    "imageCount": 10,
    "sourceFolder": "05. Consistent Hashing"
  },
  {
    "id": "06-key-value-store",
    "order": 6,
    "title": "Chapter 6: Design a Key-Value Store",
    "subtitle": "A key-value store is a type of non-relational database where data is stored as key-value pairs. Each key is unique, and values are accessed using these keys. Th",
    "category": "building-blocks",
    "readTime": 9,
    "imageCount": 17,
    "sourceFolder": "06. Key-Value Store"
  },
  {
    "id": "07-unique-id-generator",
    "order": 7,
    "title": "Chapter 7: Design a Unique ID Generator in Distributed Systems",
    "subtitle": "This chapter addresses the challenge of designing a unique ID generator for distributed systems. Traditional auto-increment keys are unsuitable in distributed e",
    "category": "building-blocks",
    "readTime": 5,
    "imageCount": 5,
    "sourceFolder": "07. Unique-Id Generator"
  },
  {
    "id": "08-url-shortener",
    "order": 8,
    "title": "Chapter 8: Design a URL Shortener",
    "subtitle": "This chapter discusses the design of a URL shortening service like TinyURL. The system's main goals include URL shortening, redirecting, and high scalability to",
    "category": "case-studies",
    "readTime": 5,
    "imageCount": 7,
    "sourceFolder": "08. URL Shortener"
  },
  {
    "id": "09-web-crawler",
    "order": 9,
    "title": "Chapter 9: Design a Web Crawler",
    "subtitle": "A web crawler, also known as a spider or robot, is used to discover and collect web content, such as web pages, images, and videos. This chapter focuses on desi",
    "category": "case-studies",
    "readTime": 5,
    "imageCount": 4,
    "sourceFolder": "09. Web Crawler"
  },
  {
    "id": "10-notification-system",
    "order": 10,
    "title": "Chapter 10: Design a Notification System",
    "subtitle": "A notification system is essential for modern applications, providing timely updates like product notifications, events, offers, and alerts. Notifications can b",
    "category": "case-studies",
    "readTime": 5,
    "imageCount": 6,
    "sourceFolder": "10. Notification System"
  },
  {
    "id": "11-news-feed-system",
    "order": 11,
    "title": "Chapter 11: Design a News Feed System",
    "subtitle": "A news feed system displays a constantly updating list of posts (status updates, photos, videos, and links) from a user’s connections. Examples include Facebook",
    "category": "case-studies",
    "readTime": 5,
    "imageCount": 5,
    "sourceFolder": "11. News Feed System"
  },
  {
    "id": "12-chat-system",
    "order": 12,
    "title": "Chapter 12: Design a Chat System",
    "subtitle": "A chat system supports real-time messaging between users. This chapter focuses on designing a chat app that includes:",
    "category": "case-studies",
    "readTime": 6,
    "imageCount": 16,
    "sourceFolder": "12. Chat System"
  },
  {
    "id": "13-search-autocomplete",
    "order": 13,
    "title": "Chapter 13: Design a Search Autocomplete System",
    "subtitle": "Autocomplete, also known as typeahead or incremental search, provides real-time suggestions to users as they type in search boxes. The system must efficiently d",
    "category": "case-studies",
    "readTime": 5,
    "imageCount": 9,
    "sourceFolder": "13. Search Autocomplete"
  },
  {
    "id": "14-youtube",
    "order": 14,
    "title": "Chapter 14: Design YouTube",
    "subtitle": "YouTube is a massive video streaming platform supporting video uploads, playback, and various interactions. This chapter focuses on designing a scalable video s",
    "category": "case-studies",
    "readTime": 6,
    "imageCount": 14,
    "sourceFolder": "14. Youtube"
  },
  {
    "id": "15-google-drive",
    "order": 15,
    "title": "Chapter 15: Design Google Drive",
    "subtitle": "Google Drive is a cloud-based file storage and synchronization service that allows users to store, access, and share files from various devices. This chapter di",
    "category": "case-studies",
    "readTime": 7,
    "imageCount": 9,
    "sourceFolder": "15. Google Drive"
  },
  {
    "id": "16-proximity-service",
    "order": 16,
    "title": "Chapter 16: Proximity Service",
    "subtitle": "A proximity service is designed to find nearby locations, such as restaurants, hotels, gas stations, and other businesses. This functionality is used in applica",
    "category": "case-studies",
    "readTime": 9,
    "imageCount": 15,
    "sourceFolder": "16. Proximity Service"
  },
  {
    "id": "17-nearby-friends",
    "order": 17,
    "title": "Chapter 17: Nearby Friends",
    "subtitle": "This chapter focuses on designing a scalable backend for an application which enables user to share their location and discover friends who are nearby.",
    "category": "case-studies",
    "readTime": 11,
    "imageCount": 10,
    "sourceFolder": "17. Nearby Friends"
  },
  {
    "id": "18-google-maps",
    "order": 18,
    "title": "Chapter 18: Google Maps",
    "subtitle": "We'll design a simple version of Google Maps.",
    "category": "case-studies",
    "readTime": 13,
    "imageCount": 22,
    "sourceFolder": "18. Google Maps"
  },
  {
    "id": "19-distributed-message-queue",
    "order": 19,
    "title": "Chapter 19: Distributed Message Queue",
    "subtitle": "We'll be designing a distributed message queue in this chapter.",
    "category": "case-studies",
    "readTime": 22,
    "imageCount": 35,
    "sourceFolder": "19. Distributed Message Queue"
  },
  {
    "id": "20-metrics-monitoring-and-alerting-system",
    "order": 20,
    "title": "Chapter 20: Metrics Monitoring and Alerting System",
    "subtitle": "This chapter focuses on designing a highly scalable metrics monitoring and alerting system, which is critical for ensuring high availability and reliability.",
    "category": "case-studies",
    "readTime": 16,
    "imageCount": 22,
    "sourceFolder": "20. Metrics Monitoring and Alerting System"
  },
  {
    "id": "21-ad-click-event-aggregation",
    "order": 21,
    "title": "Chapter 21: Ad Click Event Aggregation",
    "subtitle": "Digital advertising is a big industry with the rise of Facebook, YouTube, TikTok, etc.",
    "category": "case-studies",
    "readTime": 19,
    "imageCount": 29,
    "sourceFolder": "21. Ad Click Event Aggregation"
  },
  {
    "id": "22-hotel-reservation-system",
    "order": 22,
    "title": "Chapter 22: Hotel Reservation System",
    "subtitle": "In this chapter, we're designing a hotel reservation system, similar to Marriott International.",
    "category": "case-studies",
    "readTime": 17,
    "imageCount": 17,
    "sourceFolder": "22. Hotel Reservation System"
  },
  {
    "id": "23-distributed-email-service",
    "order": 23,
    "title": "Chapter 23: Distributed Email Service",
    "subtitle": "We'll design a distributed email service, similar to Gmail in this chapter.",
    "category": "case-studies",
    "readTime": 12,
    "imageCount": 14,
    "sourceFolder": "23. Distributed Email Service"
  },
  {
    "id": "24-s3-like-object-storage",
    "order": 24,
    "title": "Chapter 24: S3-like Object Storage",
    "subtitle": "In this chapter, we'll be designing an object storage service, similar to Amazon S3.",
    "category": "case-studies",
    "readTime": 16,
    "imageCount": 23,
    "sourceFolder": "24. S3-like Object Storage"
  },
  {
    "id": "25-real-time-gaming-leaderboard",
    "order": 25,
    "title": "Chapter 25: Real-time Gaming Leaderboard",
    "subtitle": "We are going to design a leaderboard for an online mobile game:",
    "category": "case-studies",
    "readTime": 14,
    "imageCount": 23,
    "sourceFolder": "25. Real-time Gaming Leaderboard"
  },
  {
    "id": "26-payment-system",
    "order": 26,
    "title": "Chapter 26: Payment System",
    "subtitle": "We'll design a payment system in this chapter, which underpins all of modern e-commerce.",
    "category": "case-studies",
    "readTime": 14,
    "imageCount": 10,
    "sourceFolder": "26. Payment System"
  },
  {
    "id": "27-digital-wallet",
    "order": 27,
    "title": "Chapter 27: Digital Wallet",
    "subtitle": "Payment platforms usually have a wallet service, where they allow clients to store funds within the application, which they can withdraw later.",
    "category": "case-studies",
    "readTime": 17,
    "imageCount": 25,
    "sourceFolder": "27.  Digital Wallet"
  },
  {
    "id": "28-stock-exchange",
    "order": 28,
    "title": "Chapter 28: Stock Exchange",
    "subtitle": "We'll design an electronic stock exchange in this chapter.",
    "category": "case-studies",
    "readTime": 20,
    "imageCount": 24,
    "sourceFolder": "28. Stock Exchange"
  }
]

export function getChapterById(id: string): Chapter | undefined {
  return chapters.find((c) => c.id === id)
}

export function getChaptersByCategory(category: ChapterCategory): Chapter[] {
  return chapters.filter((c) => c.category === category)
}
